### ISSUE TITLE
system cannot find file specified

### ISSUE THREAD

**Issue by SuperrSohrab** [timsutton/brigadier#104]
When executing brigadier for MacBookPro10,1 i get the error 
Traceback (most recent call last):
  File "brigadier", line 379, in <module>
  File "brigadier", line 313, in main
  File "brigadier", line 84, in sevenzipExtract
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
[2536] Failed to execute script brigadier

is there any way to fix this?

**Comment by pb1977lpool** [comment]
I have this issue too - be grateful for any advice. Thanks

**Comment by flying4fun** [comment]
I ran into the same issue.  I resolved it by installing 7-zip. 
Try installing the 7-zip and then re-run brigadier

good luck.

**Comment by mcrisostomo** [comment]
I'm facing the same issue.

Tried to install 7-zip and nothing changes.

My macbook model is a Macbook Alumminum Late 2008 13 inch running Windows 11 23h2.

On my CMD or PowerShell, i've tried the `brigadier.exe -m Macbook5,1` and i recieve the same error.

Tried in versions 0.2.6, 0.2.5 and 0.2.4

How proceed?

----

[Edit]

Solved using another PC and running `brigadier.exe -m MacBook5,1` on CMD

**Comment by nixcamic** [comment]
This happens on Windows 11 since WMIC isn't installed by default. You can install it to fix the error.

fhttps://superuser.com/questions/1178674/wmic-is-not-recognized-as-an-internal-or-external-command-operable-program-or 

"At the time of writing (23H2), WMIC is still available as an optional feature. In the Settings app, go to System → Optional features and click "View features" in the "Add an optional feature" row. Check the box for WMIC and proceed through the installation."

Ideally someone would update this script but really at this point updating the script then going through bug testing etc. for computers this old to run W11 kinda seems like an uphill battle.
