### ISSUE TITLE
Running brigadier.exe --install on a MacbookPro2012 Retina dumps an error upon installing BootCamp

### ISSUE THREAD

**Issue by rin67630** [timsutton/brigadier#109]
I tried to run Brigadier downloaded today on a current Windows11 running on a MacbookPro 2012 Retina.

Error:
```
  File "brigadier", line 379, in <module>
  File "brigadier", line 323, in main
  File "brigadier", line 116, in installBootcamp
TypeError: sequence item 4: expected string, NoneType found
```

Here is the full log:
```
PS E:\Downloads> .\brigadier.exe --install
Using Mac model: MacBookPro10,1.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/50/29/041-84869-A_EJ35WAWA75/obofx71e3kcf8aqzukdrzg7hqpv1p06hca/BootCampESD.dst/041-84869.English.dist.

Distribution 041-84869 supports the following models: MacBookAir5,1, MacBookAir5,2.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/26/08/041-84821-A_AMCFPC3QDK/4fffs8qgdflw7pn1finqqd40gifh41mvs6/041-84821.English.dist.

Distribution 041-84821 supports the following models: MacBookAir4,1, MacBookAir4,2, MacBookAir5,1, MacBookAir5,2, MacBookPro6,1, MacBookPro6,2, MacBookPro8,1, MacBookPro8,2, MacBookPro8,3, MacBookPro9,1, MacBookPro9,2, MacPro4,1, MacPro5,1, Macmini5,1, Macmini5,2, Macmini5,3, Macmini6,1, Macmini6,2, iMac11,3, iMac12,1, iMac12,2, iMac13,1, iMac13,2, iMac13,3.
Model supported in package distribution file at https://swdist.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/041-98143.English.dist.

Distribution 041-98143 supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

There is more than one ESD product available for this model:
041-84869: PostDate 2019-10-22 15:58:17
041-84821: PostDate 2019-10-22 15:58:14
041-98143: PostDate 2019-10-10 20:43:24
Selecting 041-84869 as it's the most recently posted.
Making directory E:\Downloads\BootCamp-041-84869..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/50/29/041-84869-A_EJ35WAWA75/obofx71e3kcf8aqzukdrzg7hqpv1p06hca/BootCampESD.pkg.

100.0% 942981120 / 942980953 bytes
Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5 -y c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\BootCampESD.pkg


7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\BootCampESD.pkg

Extracting  Scripts
Extracting  Payload
Extracting  PackageInfo
Extracting  Bom
Extracting  [TOC].xml

Everything is Ok

Files: 5
Size:       943060293
Compressed: 942980953
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5 -y c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\Payload


7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\Payload

Extracting  Payload~

Everything is Ok

Size:       944170496
Compressed: 942965225
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5 -y c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\Payload~


7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\Payload~

Extracting  .
Extracting  .\Library
Extracting  .\Library\Application Support
Extracting  .\Library\Application Support\BootCamp
Extracting  .\Library\Application Support\BootCamp\WindowsSupport.dmg

Everything is Ok

Folders: 4
Files: 1
Size:       944169690
Compressed: 944170496
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe x -oE:\Downloads\BootCamp-041-84869 -y c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\WindowsSupport.dmg


7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: c:\users\mifi\appdata\local\temp\bootcamp-unpack_ptacl5\WindowsSupport.dmg

Extracting  0.Apple_ISO

Everything is Ok

Size:       1054398464
Compressed: 944169690
Installing Boot Camp...

Traceback (most recent call last):
  File "brigadier", line 379, in <module>
  File "brigadier", line 323, in main
  File "brigadier", line 116, in installBootcamp
TypeError: sequence item 4: expected string, NoneType found
[11652] Failed to execute script brigadier
```

Could you please check?

Thank you a lot.
Laszo

**Comment by rin67630** [comment]
P.S. Brigadier did not extract the BootCamp drivers in BootCamp-041-84869
but left a file AppleISO there
