### ISSUE TITLE
can't download bootcamp for MacBookAir7,1

### ISSUE THREAD

**Issue by gwl7810** [timsutton/brigadier#19]
D:\thunderdownload>brigadier.exe -m="MacBookAir7,1"
Using Mac model: =MacBookAir7,1.

Traceback (most recent call last):
  File "<string>", line 358, in <module>
  File "<string>", line 217, in main
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 126, in urlopen
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 406, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 519, in http_response
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 444, in error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 378, in _call_chain
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2",
ine 527, in http_error_default
urllib2.HTTPError: HTTP Error 502: Bad Gateway

**Comment by timsutton** [comment]
502 seems like an error on Apple's servers - it's working fine here. I'd recommend trying from 1) another machine, and/or 2) an OS X system (by running the `brigadier` source file directly).

**Comment by nathanmcnulty** [comment]
Seems to be working fine now. Just pulled down and installed 031-55710 on a MacBookAir7,1. Must have been just an outage or something.
