### ISSUE TITLE
ioerror: [Errno socket error] [Errno 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by jbinaz** [timsutton/brigadier#27]
Any thoughts on why we would be getting this error all the sudden?

C:\Users\admin>C:\BootCamp\brigadier.exe --install --keep-files --output-dir=C:\BootCamp
Using Mac model: MacBookAir7,2.

Model supported in package distribution file at http://swcdn.apple.com/content/downloads/39/14/031-55710/u2c6bi4yl91ud1lqc3k53bx9860hvsnf7z/031-55710.English.dist.

Distribution 031-55710 supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

Final output path C:\BootCamp\BootCamp-031-55710 already exists, removing it...

Making directory C:\BootCamp\BootCamp-031-55710..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/39/14/031-55710/u2c6bi4yl91ud1lqc3k53bx9860hvsnf7z/BootCampESD.pkg.

100.0% 1614454784 / 1614454648 bytes
Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "<string>", line 283, in main
  File "<string>", line 62, in downloadFile
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 93, in urlretrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 239, in retrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 358, in open_http
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 664, in http_error_301
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 450, in open_https
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 358, in open_http
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 664, in http_error_301
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 358, in open_http
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 436, in open_https
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 954, in endheaders
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 814, in _send_output
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 776, in send
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 1161, in connect
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 381, in wrap_socket
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 143, in __init__
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 305, in do_handshake
IOError: [Errno socket error] [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by jbinaz** [comment]
This ended up being a firewall issue on our side so closing.
