### ISSUE TITLE
Brigadier Fails at 7Zip Extraction

### ISSUE THREAD

**Issue by Mrjamin** [timsutton/brigadier#37]
Hi,

Thanks for taking the time to develop this tool.  I'm getting a failure at the point Brigadier is trying to extract the 7zip file.  Here's the console ouput:

...
Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/39/14/031-55710/u2c6bi4yl91ud1lqc3k53bx9860hvsnf7z/BootCampESD.pkg.

100.0% 1614454784 / 1614454648 bytes
100.4% 1662976 / 1655808 bytes
Downloaded 7-zip to c:\users\ben\appdata\local\temp\tmpvcaver\7z1514-x64.msi.

We need to install 7-Zip..

7-Zip install returned exit code 1603.

Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\ben\appdata\local\temp\bootcamp-unpack_ifd_bk -y c:\users\ben\appdata\local\temp\bootcamp-unpack_ifd_bk\BootCampESD.pkg

Traceback (most recent call last):
  File "<string>", line 358, in <module>
  File "<string>", line 309, in main
  File "<string>", line 86, in sevenzipExtract
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\subprocess", line 493, in call
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\subprocess", line 679, in __init__
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\subprocess", line 896, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

Not sure if this is a bug or something with my system, so any thoughts would be greatly appreciated.

**Comment by dinamic** [comment]
Thanks for reporting this issue. It also happens on my Windows 10.

**Comment by nathanmcnulty** [comment]
The last time I built an installer for this was a couple of years ago, so take this with a grain of salt... The installer that Apple created only seems to work properly when run as SYSTEM (similar to root on macOS). When you try to execute the installer via setup.exe or  by using msiexec, the install generally fails due to either timing out or some other error. I believe they did this because it was only intended to be run via the Bootcamp installer which installs it as part of the unattended setup of Windows.

At one point, I re-wrote this whole application as a Powershell script which created a scheduled task to run the setup.exe installer as SYSTEM. I had played with using PsExec, but some AV's were flagging it is a "hacking" tool... PsExec is obviously the easier one to test with and evaluate, so you could give that a try and see if that works better for you. I may be able to go back and find my last version of the script, but I haven't validated it in a couple of years since I moved into an InfoSec role.

**Comment by dinamic** [comment]
I found out that brigadier works fine should it be started in an elevated command prompt. I guess only tech skilled people would try to fix their macbook drivers, so I would question whether any changes are needed at this point. Error messages are pretty clear on what the issue is and one could fix them with ease.

Maybe the prerequisites should be more clearer.

1. Have 7zip installed.
2. Run brigadier in an elevated shell.

**Comment by bhaveshsood13** [comment]
So it doesn't work even after running in cmd with administrator rights having installed 7zip already .
Though there is a  workaround. All you need to do is go to 
`c:\users\nickpe~1\appdata\local\temp\bootcamp-unpack_udazk8
`
wherever the 7-Zip command was called , and then there extract that pkg file with 7-Zip by right clicking and extract here with 7-Zip . 
After that open the file with 7-Zip and you'll be able to see the folders , then you can install the drivers as you want.

**Comment by milahu** [comment]
im getting a similar error

```
ERROR: Data Error : Windows6.1-KB2685811-x64.cab
ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
ERROR: Data Error : Windows6.1-KB2685811-x64.xml
```

<details>

```
PS C:\Users\user\Downloads\brigadier> C:\Python27\python.exe brigadier
Using Mac model: MacBookPro11,1.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/041-98143.English.dist.

Distribution 041-98143 supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

Making directory C:\Users\user\Downloads\brigadier\BootCamp-041-98143..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg.

100.0% 1614471168 / 1614464893 bytes
Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw -y c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\BootCampESD.pkg


7-Zip 23.00 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-05-07

Scanning the drive for archives:
1 file, 1614464893 bytes (1540 MiB)

Extracting archive: c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\BootCampESD.pkg
--
Path = c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\BootCampESD.pkg
Type = Xar
Physical Size = 1614464893
SubType = pkg
Headers Size = 4209
----
Path = Payload
Size = 1614449168
Packed Size = 1614449168
Modified = 2016-03-31 22:21:12.0000000
Created = 2016-03-31 22:21:32.0000000
Accessed = 2016-03-31 22:15:12.0000000
Mode = -rw-r--r--
User = root
Group = wheel
Method = octet-stream
--
Path = Payload
Type = bzip2

Everything is Ok

Size:       1613847552
Compressed: 1614464893
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw -y c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\Payload~


7-Zip 23.00 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-05-07

Scanning the drive for archives:
1 file, 1613847552 bytes (1540 MiB)

Extracting archive: c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\Payload~

WARNINGS:
There are data after the end of archive

--
Path = c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\Payload~
Type = Cab
WARNINGS:
There are data after the end of archive
Offset = 2177233
Physical Size = 794777
Tail Size = 1610875542
Method = MSZip
Blocks = 1
Volumes = 1
Volume Index = 0
ID = 0

ERROR: Data Error : Windows6.1-KB2685811-x64.cab
ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
ERROR: Data Error : Windows6.1-KB2685811-x64.xml

Sub items Errors: 3

Archives with Errors: 1

Warnings: 1

Sub items Errors: 3
Command failure: C:\Program Files\7-Zip\7z.exe e -oc:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw -y c:\users\user\appdata\local\temp\bootcamp-unpack_xsp1fw\Payload~ exited 2.
```

</details>


> To have it fixed, I have manually downloaded and installed 7zip in its default folder.

yes

```
& 'C:\Program Files\7-Zip\7z.exe' e -o$HOME\appdata\local\temp\bootcamp-unpack_xsp1fw -y $HOME\appdata\local\temp\bootcamp-unpack_xsp1fw\Payload~
```

... will create `Library\Application Support\BootCamp\WindowsSupport.dmg`


```
& 'C:\Program Files\7-Zip\7z.exe' e -o$HOME\appdata\local\temp\bootcamp-unpack_xsp1fw -y "$HOME\appdata\local\temp\bootcamp-unpack_xsp1fw\Library\Application Support\BootCamp\WindowsSupport.dmg"
```

... will create more files in `Library\Application Support\BootCamp`

now run `Library\Application Support\BootCamp\BootCamp\setup.exe`
and afterwards, delete the temporary files in `$HOME\appdata\local\temp\bootcamp-unpack_xsp1fw`

~~wild guess: maybe the downloaded file is not fully flushed to disk, so `7z` sees an incomplete file?~~
no, it really is a bug in 7z 23.01

**Comment by mo-g** [comment]
Just got a similar issue with a MacBook7,2 using latest release of Brig and a manually downloaded 7zip - on Windows 10; using the latest release .exe. Also ran as "SU" following advice in this thread, then tried manually downloading BootCampESD from the link in the CLI logs and extracting with 7z. Payload extraction also fails there.

Could this be a regression in 7z itself?

**Comment by lstriegher** [comment]
> Could this be a regression in 7z itself?

Yeah, it seems like a regression in 7z. The older version 7-Zip 19.00 (2019-02-21) worked fine for me, unlike the newest versions (Not sure about releases between the two).

**Comment by jameswsullivan** [comment]
I can confirm that this seems to be a 7zip issue. I get the same errors:

```
ERROR: Data Error : Windows6.1-KB2685811-x64.cab
ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
ERROR: Data Error : Windows6.1-KB2685811-x64.xml
```

And manually extracting the files with 7zip was unsuccessful as well, 7zip prompts ".... there's some data at the end of the archive ..." and extraction fails.

Uninstalling the latest 7zip `7-Zip 23.01 (2023-06-20)` and installing the previous version `7-Zip 22.01 (2022-07-15)` resolved the issue.

**Comment by inbirth** [comment]
> I can confirm that this seems to be a 7zip issue. I get the same errors:
> 
> ```
> ERROR: Data Error : Windows6.1-KB2685811-x64.cab
> ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
> ERROR: Data Error : Windows6.1-KB2685811-x64.xml
> ```
> 
> And manually extracting the files with 7zip was unsuccessful as well, 7zip prompts ".... there's some data at the end of the archive ..." and extraction fails.
> 
> Uninstalling the latest 7zip `7-Zip 23.01 (2023-06-20)` and installing the previous version `7-Zip 22.01 (2022-07-15)` resolved the issue.

**THANK YOU! jameswsullivan**

we must have been working on this at the same time, because I can confirm this is a 7-zip 23.01 issue also. Immediately downgrading resolved this problem with the following error of:

> ```
> ERROR: Data Error : Windows6.1-KB2685811-x64.cab
> ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
> ERROR: Data Error : Windows6.1-KB2685811-x64.xml
> ```

I don't even use this account and I haven't logged in for years, this was one of those times where I had to login to say thank you so much for discovering this. This was driving me up the wall I was about to purchase a license for magic utilities because the trial is very nice and so easy, but now we can finally do something as simple as scroll with this magic mouse. xD

You are a life saver. I have 7zip 22.01 installed and I have placed to brigadier to my desktop. Navigated to my desktop while in command prompt (admin) and have successfully executed this command:

> ```
> brigadier.exe -m MacBookPro14,1
> ```

Now I have all the files extracted into a bootcamp folder with all the files successfully extracted. Installed the AppleWirelessMouse64 in the BootCamp\Drivers\Apple directory, I don't even think i needed to restart.
this is groundbreaking! I can confirm this works in windows 11 x64. Thank you again

**Comment by milahu** [comment]
upstream issue:
["ERROR: Data Error". cpio archive is interpreted as cab archive. regression from 7z 22.01 to 7z 23.01](https://sourceforge.net/p/sevenzip/bugs/2414/)

workaround: use `cpio` to extract files from `Payload~`

```
$ 7z x BootCampESD.pkg

$ file -i Payload~
Payload~: application/x-cpio; charset=binary

$ sha256sum Payload~
390b4f393a979835224e19b749056ab0c2a4bdfa9845d632c3c5d39dfb55963a  Payload~

$ cpio --extract --verbose <Payload~
.
./Library
./Library/Application Support
./Library/Application Support/BootCamp
./Library/Application Support/BootCamp/WindowsSupport.dmg
3152046 blocks

$ sha256sum "Library/Application Support/BootCamp/WindowsSupport.dmg"
7c84ace54a095156e6f57da3ba825baf87b9f67308b39099c65b308a94461066  Library/Application Support/BootCamp/WindowsSupport.dmg
```

**Comment by milahu** [comment]
> workaround: use `cpio` to extract files from `Payload~`

i tried to replace 7z with bsdtar of [libarchive](https://github.com/libarchive/libarchive) which is [part of windows 10](https://www.bleepingcomputer.com/news/microsoft/built-in-tar-and-curl-utilities-to-be-included-in-windows/) since 2017
but [bsdtar fails to extract dmg archives](https://github.com/libarchive/libarchive/issues/156)

<details>

```sh
wget http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg

du -sh BootCampESD.pkg
# 1.6G    BootCampESD.pkg

sha256sum BootCampESD.pkg
# f72f3d43355321f35432a25432b2c56cd66df34997fa14a0e66830f456e5da7a  BootCampESD.pkg

file -i BootCampESD.pkg
# BootCampESD.pkg: application/x-xar; charset=binary
```

```sh
bsdtar -h | tail -n1
# bsdtar 3.6.2 - libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.3 bz2lib/1.0.8 libzstd/1.5.5

mkdir BootCampESD
bsdtar -x -f BootCampESD.pkg -C BootCampESD

# note: bsdtar produces a different Payload file than 7z
# bsdtar preserves the bzip2 compression
# 7z removes the bzip2 compression

file -i BootCampESD/Payload
# BootCampESD/Payload: application/x-bzip2; charset=binary

sha256sum BootCampESD/Payload
# 531ea579fbee692a569b5214920f4313d48b8cf970c1259b05054fedf5ef74bc  BootCampESD/Payload

mkdir Payload
bsdtar -x -f BootCampESD/Payload -C Payload

# note: here, bsdtar removes the bzip2 compression of Payload

sha256sum "Payload/Library/Application Support/BootCamp/WindowsSupport.dmg"
# 7c84ace54a095156e6f57da3ba825baf87b9f67308b39099c65b308a94461066  Payload/Library/Application Support/BootCamp/WindowsSupport.dmg

bsdtar -x -f "Payload/Library/Application Support/BootCamp/WindowsSupport.dmg" -C WindowsSupport
# bsdtar: Error opening archive: Unrecognized archive format
```

</details>

alternative: [peazip](https://github.com/peazip/PeaZip) but that is a gui tool

so... either/or

- back to 7z 22.01
- use bsdtar for BootCampESD.pkg and Payload and 7z 23.01 for WindowsSupport.dmg

---


to reduce disk writes, the 3 extraction steps should be done in memory

<details>

```sh
du -sh *
# 1.6G    BootCampESD
# 1.6G    BootCampESD.pkg
# 1.6G    Payload
# 2.6G    WindowsSupport

rm -rf BootCampESD Payload WindowsSupport

mkdir WindowsSupport
cd WindowsSupport
cat ../BootCampESD.pkg |
bsdtar -x -O Payload |
bsdtar -x -O "Library/Application Support/BootCamp/WindowsSupport.dmg" |
7z x /dev/stdin
# ERROR: /dev/stdin
# Can not open the file as archive
cd ..
rm -rf WindowsSupport
```

7z fails to extract from stdin, so at least 2 steps can be piped

```sh
cat BootCampESD.pkg |
bsdtar -x -O Payload |
bsdtar -x "Library/Application Support/BootCamp/WindowsSupport.dmg"

mkdir WindowsSupport
cd WindowsSupport
7z x ../"Library/Application Support/BootCamp/WindowsSupport.dmg"
cd ..
```

we also can pipe the http request

```sh
curl -s http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg |
bsdtar -x -O Payload |
bsdtar -x "Library/Application Support/BootCamp/WindowsSupport.dmg"

mkdir WindowsSupport
cd WindowsSupport
7z x ../"Library/Application Support/BootCamp/WindowsSupport.dmg"
cd ..
```

</details>

**Comment by magicalne** [comment]
Similar issue here. 🖐 I got it to work by:

- Manually downloading an older version of 7-Zip: [7-Zip 19.00 (2019-02-21) for Windows](https://www.7-zip.org/download.html)
- Opening PowerShell as an administrator and running: .\brigadier.exe -k -i

**Comment by vantheshark** [comment]
> I can confirm that this seems to be a 7zip issue. I get the same errors:
> 
> ```
> ERROR: Data Error : Windows6.1-KB2685811-x64.cab
> ERROR: Data Error : Windows6.1-KB2685811-x64-pkgProperties.txt
> ERROR: Data Error : Windows6.1-KB2685811-x64.xml
> ```
> 
> And manually extracting the files with 7zip was unsuccessful as well, 7zip prompts ".... there's some data at the end of the archive ..." and extraction fails.
> 
> Uninstalling the latest 7zip `7-Zip 23.01 (2023-06-20)` and installing the previous version `7-Zip 22.01 (2022-07-15)` resolved the issue.

It indeed is 7zip problem. I used suggested version and managed to un-zip the package 👇🏻 

```shell
E:\tmp>brigadier -m MacBookPro14,3 -o MacBookPro14.3
Using Mac model: MacBookPro14,3.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/47/29/041-89072-A_HZY5QI4LGV/knck1r3qmsw9nliisjjm7vll0zv1u239eu/041-89072.English.dist.

Distribution 041-89072 supports the following models: MacBookPro14,3.

Final output path MacBookPro14.3\BootCamp-041-89072 already exists, removing it...

Making directory MacBookPro14.3\BootCamp-041-89072..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/47/29/041-89072-A_HZY5QI4LGV/knck1r3qmsw9nliisjjm7vll0zv1u239eu/BootCampESD.pkg.

100.0% 809738240 / 809731463 bytes
Downloaded 7-zip to c:\users\myname\appdata\local\temp\tmpirquu9\7z2201-x64.msi.

We need to install 7-Zip..

7-Zip install returned exit code 0.

Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku -y c:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku\BootCampESD.pkg

Traceback (most recent call last):
  File "brigadier", line 379, in <module>
  File "brigadier", line 313, in main
  File "brigadier", line 84, in sevenzipExtract
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
[2264] Failed to execute script brigadier

E:\tmp>"C:\Program Files\7-Zip\7z.exe" e -oc:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku -y c:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku\BootCampESD.pkg
The system cannot find the path specified.

E:\tmp>"C:\Program Files (x86)\7-Zip\7z.exe" e -oc:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku -y c:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku\BootCampESD.pkg

7-Zip 22.01 (x86) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 809731463 bytes (773 MiB)

Extracting archive: c:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku\BootCampESD.pkg

WARNINGS:
There are data after the end of archive

--
Path = c:\users\myname\appdata\local\temp\bootcamp-unpack_ghr4ku\BootCampESD.pkg
Type = Xar
WARNINGS:
There are data after the end of archive
Physical Size = 809729833
Tail Size = 1630
SubType = pkg
Headers Size = 4211
----
Path = Payload
Size = 809714113
Packed Size = 809714113
Modified = 2017-04-20 05:51:16.0000000
Created = 2017-04-20 05:51:28.0000000
Accessed = 2017-04-20 05:48:23.0000000
Mode = -rw-r--r--
User = root
Group = wheel
Method = octet-stream
--
Path = Payload
Type = bzip2

Everything is Ok

Archives with Warnings: 1

Warnings: 1
Size:       807774720
Compressed: 80973146
```
