### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Vinedoo** [timsutton/brigadier#43]
Hi,

Please help, What could be the cause of this error 403: Forbidden. It was downloading yesterday, but due to not enough space, it failed during extraction. Therefore, I erased the windows partition and reinstall in a bigger partition size this time, but now this error occured.

C:\Users\User\Downloads\brigadier-0.2.4\brigadier-0.2.4>brigadier.exe -o testing -m MacBookAir 7,2
Using Mac model: MacBookAir.

Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "<string>", line 186, in main
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 126, in urlopen
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 406, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 519, in http_response
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 444, in error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 378, in _call_chain
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib2", line 527, in http_error_default
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by jonapgartwohat** [comment]
I got the same error on a VPN. Disconnecting from VPN solved it.
