### ISSUE TITLE
LookupError: unknown encoding: cp65001 when system locale is set to UTF-8

### ISSUE THREAD

**Issue by tkafka** [timsutton/brigadier#55]
Running Brigadier produces this error:

```
Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "<string>", line 168, in main
  File "<string>", line 24, in status
LookupError: unknown encoding: cp65001
```

Windows locale settings:

![Screenshot 2021-06-22 170831](https://user-images.githubusercontent.com/876717/122950182-8b376180-d37c-11eb-80dd-ba9ed5c531ef.png)

**Comment by lnu** [comment]
I had the same issue with powershell but running it with a plain cmd worked.

**Comment by fcrespo82** [comment]
I have the same issue and running with plain cmd did not work. How to fix this?
