### ISSUE TITLE
Error on Mid2013 MBAirs

### ISSUE THREAD

**Issue by bondurantdt** [timsutton/brigadier#6]
Hello,

I am seeing this error when running both the exe on Windows or executing the python script on OSX.  I have a custom .plist that I have been using with success that points to our local SUS server.  There were two recent ESDs (091-7571 and 091-5062) that were released that I am wondering if it is having issues with, as I have run this tool successfully before on the same model.  Other models, at least the ones I have tested, do not have issues.  Here is the error when running the script.

Using Mac model: MacBookAir6,2.

Traceback (most recent call last):
  File "./brigadier", line 324, in <module>
    main()
  File "./brigadier", line 197, in main
    distfd = urllib2.urlopen(disturl)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

If I run the tool without the plist and go to Apple's SUS it is fine.  Here is the plist I am using.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CatalogURL</key>
    <string>http://myservername.coolplace.org:8088/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog</string>
</dict>
</plist>

Here are the logs of the client on the SUS server:

10.10.18.109 - - [03/Oct/2013:13:51:34 -0400] 80 GET "/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" 200 1983902 "-" "Python-urllib/2.7"
10.10.18.109 - - [03/Oct/2013:13:56:43 -0400] 80 GET "/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" 200 1983902 "-" "Python-urllib/2.7"
10.10.18.109 - - [03/Oct/2013:14:10:43 -0400] 80 GET "/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" 200 1983902 "-" "Python-urllib/2.7"
10.10.18.109 - - [03/Oct/2013:14:11:10 -0400] 80 GET "/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" 200 1983902 "-" "Python-urllib/2.7"
10.10.18.109 - - [03/Oct/2013:14:11:24 -0400] 80 GET "/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" 200 1983902 "-" "Python-urllib/2.7"

Let me know if I am missing something and thanks again for your work on this script, it is great!

**Comment by nathanmcnulty** [comment]
Tested remotely on one of our MacbookAir6,2's, and this is working with both our internal SUS and externally using Apple's CDN. The only real improvement here would be maybe some more verbose logging for troubleshooting purposes.
