### ISSUE TITLE
BootCampESD file is corrupted.

### ISSUE THREAD

**Issue by TwitchyDawdler** [timsutton/brigadier#64]
I've run Brigadier several times to download the BootCampESD file for MacBook Pro 5,3 but can't finish unpacking it using 7ZIP or the native unpacker on MacOS. I also tried downloading it directly using the URL shown in the Brigadier console window, but no luck there either, so I can only assume the file is FUBAR. The file is 041-84868. I tried contacting Apple support about it but they maintain that it is not an Apple site, even though I'm pretty sure that it is.
The URL for it is: 
https://swcdn.apple.com/content/downloads/57/55/041-84868-A_402D0DFI39/6uz8hhgtd4b87t00mrq0uihiop5ivumsbk/BootCampESD.pkg

**Comment by jeansordes** [comment]
> can't finish unpacking it using 7ZIP or the native unpacker on MacOS

What do you mean by that ? What error message do you get ?

**Comment by sreekumarr84** [comment]
I am facing a similar error on my PC. On running with model *brigadier.exe -m iMac19,2* the total download size is always greater than expected. Pasting full error.

```
Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/48/61/061-97204/zjcotww2iqibyvy6wbx3q9d50ca4lhig85/BootCampESD.pkg.

100.0% 695410688 / 695406870 bytes
Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "<string>", line 283, in main
  File "<string>", line 62, in downloadFile
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 93, in urlretrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 239, in retrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 358, in open_http
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 664, in http_error_301
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 436, in open_https
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 954, in endheaders
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 814, in _send_output
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 776, in send
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 1161, in connect
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 381, in wrap_socket
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 143, in __init__
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 305, in do_handshake
IOError: [Errno socket error] [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
