### ISSUE TITLE
Exception after downloading .pkg

### ISSUE THREAD

**Issue by br3nt** [timsutton/brigadier#73]
I get the following exception when using the tool:

<pre>
C:\Users\xxxx\Downloads>brigadier.exe -i
Using Mac model: iMac11,2.

Model supported in package distribution file at http://swcdn.apple.com/content/downloads/57/55/041-84868-A_402D0DFI39/6uz8hhgtd4b87t00mrq0uihiop5ivumsbk/BootCampESD.dst/041-84868.English.dist.

Distribution 041-84868 supports the following models: MacBook2,1, MacBook3,1, MacBook4,1, MacBook5,1, MacBook5,2, MacBook5,3, MacBook6,1, MacBook7,1, MacBookAir1,1, MacBookAir2,1, MacBookAir3,1, MacBookAir3,2, MacBookPro2,1, MacBookPro2,2, MacBookPro3,1, MacBookPro4,1, MacBookPro5,1, MacBookPro5,2, MacBookPro5,3, MacBookPro5,4, MacBookPro5,5, MacBookPro6,1, MacBookPro6,2, MacBookPro7,1, MacBookPro8,1, MacBookPro8,2, MacBookPro8,3, MacPro1,1, MacPro2,1, MacPro3,1, MacPro4,1, MacPro5,1, Macmini2,1, Macmini3,1, Macmini4,1, iMac5,1, iMac6,1, iMac7,1, iMac8,1, iMac9,1, iMac11,1, iMac11,2, iMac11,3, iMac12,1, iMac12,2.

Model supported in package distribution file at http://swcdn.apple.com/content/downloads/04/44/041-84708/yq9w47gthzu8e8fqmad6hx0vs15fuk4540/041-84708.English.dist.

Distribution 041-84708 supports the following models: MacBook2,1, MacBook3,1, MacBook4,1, MacBook5,1, MacBook5,2, MacBook5,3, MacBook6,1, MacBook7,1, MacBookAir1,1, MacBookAir2,1, MacBookAir3,1, MacBookAir3,2, MacBookPro2,1, MacBookPro2,2, MacBookPro3,1, MacBookPro4,1, MacBookPro5,1, MacBookPro5,2, MacBookPro5,3, MacBookPro5,4, MacBookPro5,5, MacBookPro6,1, MacBookPro6,2, MacBookPro7,1, MacBookPro8,1, MacBookPro8,2, MacBookPro8,3, MacPro1,1, MacPro2,1, MacPro3,1, MacPro4,1, MacPro5,1, Macmini2,1, Macmini3,1, Macmini4,1, iMac5,1, iMac6,1, iMac7,1, iMac8,1, iMac9,1, iMac11,1, iMac11,2, iMac11,3, iMac12,1, iMac12,2.

There is more than one ESD product available for this model:
041-84868: PostDate 2019-10-22 15:58:15
041-84708: PostDate 2019-10-16 22:15:07
Selecting 041-84868 as it's the most recently posted.
Final output path C:\Users\xxxx\Downloads\BootCamp-041-84868 already exists, removing it...

Making directory C:\Users\xxxx\Downloads\BootCamp-041-84868..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/57/55/041-84868-A_402D0DFI39/6uz8hhgtd4b87t00mrq0uihiop5ivumsbk/BootCampESD.pkg.

100.0% 632610816 / 632605139 bytes
Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "<string>", line 283, in main
  File "<string>", line 62, in downloadFile
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 93, in urlretrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 239, in retrieve
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 358, in open_http
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 371, in http_error
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 664, in http_error_301
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 634, in http_error_302
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 660, in redirect_internal
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 207, in open
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\urllib", line 436, in open_https
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 954, in endheaders
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 814, in _send_output
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 776, in send
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\httplib", line 1161, in connect
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 381, in wrap_socket
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 143, in __init__
  File "c:\jenkins\workspace\brigadier\build\brigadier\out00-PYZ.pyz\ssl", line 305, in do_handshake
IOError: [Errno socket error] [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

C:\Users\xxxx\Downloads>
</pre>

**Comment by JonnyTech** [comment]
> IOError: [Errno socket error] [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Looks like a connection error with swcdn.apple.com - I suspect that you are either running an old version of Windows (ie Windows 7) or an old version of Python.

**Comment by timsutton** [comment]
I can reproduce this in a Windows 11 VM, using the self-contained brigadier executable. I think it's actually not having a connection error with swcdn.apple.com, but rather when it tries to download 7-Zip on-demand from https://www.7-zip.org/download.html.

You can work around this for now by downloading 7-Zip from the above URL and installing it before running brigadier, but I'll likely need to address this by packaging up a (much) newer exe with a newer Python distribution.

**Comment by timsutton** [comment]
@br3nt Please give the [0.2.5 release](https://github.com/timsutton/brigadier/releases/tag/0.2.5) a shot and let me know if it resolves the issue for you?
