### ISSUE TITLE
brigadier crashes on startup

### ISSUE THREAD

**Issue by a-marmot** [timsutton/brigadier#75]
brigadier crashes even if run as an administrator, with Windows 7 compatibility.  Mac Pro 5,1 running Windows 22H2.

**Comment by InaliRahl** [comment]
This happens to me too. Windows 10, MacBookPro5,5.

Here is the log:

C:\Users\User>C:\Users\User\Desktop\brigadier.exe
Using Mac model: MacBookPro5,5.

Traceback (most recent call last):
  File "brigadier", line 370, in <module>
  File "brigadier", line 194, in main
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 429, in open
  File "urllib2.py", line 447, in _open
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 1241, in https_open
  File "urllib2.py", line 1198, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
[2328] Failed to execute script brigadier

**Comment by timsutton** [comment]
I can reproduce this on Windows 7, thanks for the repro on Windows 10.

**Comment by timsutton** [comment]
For those of you affected, if you install 7-Zip (latest 64-bit build) from [here](https://www.7-zip.org/download.html) _before_ running brigadier, does this help?

**Comment by timsutton** [comment]
I think the 0.2.6 release from today should address the issue. Anyone able to confirm?

**Comment by KimonoDraggin** [comment]
> I think the 0.2.6 release from today should address the issue. Anyone able to confirm?

I have 7zip from your link downloaded and when i try to run Brig.exe (0.2.6) it opens cmd then still just closes....semms to do nothing. (on win11 fully updated)

**Comment by basharalbashier** [comment]
Is this issue related to network connection?
