### ISSUE TITLE
[Error 2] The system cannot find the file specified [10096] Failed to execute script brigadier

### ISSUE THREAD

**Issue by desaitechindia** [timsutton/brigadier#81]
brigadier.exe --model MacBookAir7,2
Using Mac model: MacBookAir7,2.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/041-98143.English.dist.

Distribution 041-98143 supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

Final output path C:\Users\Gurudev\Downloads\WinMac\BootCamp-041-98143 already exists, removing it...

Making directory C:\Users\Gurudev\Downloads\WinMac\BootCamp-041-98143..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg.

100.0% 1614471168 / 1614464893 bytes
Downloaded 7-zip to c:\users\gurudev\appdata\local\temp\tmpanlitc\7z2201-x64.msi.

We need to install 7-Zip..

7-Zip install returned exit code 1603.

Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\gurudev\appdata\local\temp\bootcamp-unpack_q5dgsh -y c:\users\gurudev\appdata\local\temp\bootcamp-unpack_q5dgsh\BootCampESD.pkg

Traceback (most recent call last):
  File "brigadier", line 379, in <module>
  File "brigadier", line 313, in main
  File "brigadier", line 84, in sevenzipExtract
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
[10096] Failed to execute script brigadier

Please HELP.

**Comment by ghost** [comment]
I got the same error. After installing 7-zip manually, it was gone.

**Comment by desaitechindia** [comment]
Oho...Great, Let me try it.

Secondly, I an having issues with Mac and Windows SSD Partitioning.

Can also post pictures of it so that you can have better idea / understanding.

**Comment by desaitechindia** [comment]
Wow...Superb.

It has worked out.

brigadier.exe --model MacBookAir7,2
Using Mac model: MacBookAir7,2.

Model supported in package distribution file at https://swdist.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/041-98143.English.dist.

Distribution 041-98143 supports the following models: MacBook8,1, MacBookAir5,1, MacBookAir5,2, MacBookAir6,1, MacBookAir6,2, MacBookAir7,1, MacBookAir7,2, MacBookPro9,1, MacBookPro9,2, MacBookPro11,1, MacBookPro11,2, MacBookPro11,3, MacBookPro11,4, MacBookPro11,5, MacBookPro12,1, MacPro6,1, Macmini6,1, Macmini6,2, Macmini7,1, iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2, iMac14,3, iMac14,4, iMac15,1.

Final output path C:\Users\Gurudev\Downloads\WinMac\BootCamp-041-98143 already exists, removing it...

Making directory C:\Users\Gurudev\Downloads\WinMac\BootCamp-041-98143..

Fetching Boot Camp product at URL http://swcdn.apple.com/content/downloads/62/58/041-98143-A_HN8B941A1T/nknv1gt3xcgylggwc11kl5e0j4296tjfo1/BootCampESD.pkg.

100.0% 1614471168 / 1614464893 bytes
Extracting...

Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru -y c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\BootCampESD.pkg


7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 1614464893 bytes (1540 MiB)

Extracting archive: c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\BootCampESD.pkg
--
Path = c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\BootCampESD.pkg
Type = Xar
Physical Size = 1614464893
SubType = pkg
Headers Size = 4209
----
Path = Payload
Size = 1614449168
Packed Size = 1614449168
Modified = 2016-04-01 01:51:12.0000000
Created = 2016-04-01 01:51:32.0000000
Accessed = 2016-04-01 01:45:12.0000000
Mode = -rw-r--r--
User = root
Group = wheel
Method = octet-stream
--
Path = Payload
Type = bzip2

Everything is Ok

Size:       1613847552
Compressed: 1614464893
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe e -oc:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru -y c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\Payload~


7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 1613847552 bytes (1540 MiB)

Extracting archive: c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\Payload~
--
Path = c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\Payload~
Type = Cpio
Physical Size = 1613847552
SubType = Portable ASCII

Everything is Ok

Folders: 4
Files: 1
Size:       1613846904
Compressed: 1613847552
Calling 7-Zip command: C:\Program Files\7-Zip\7z.exe x -oC:\Users\Gurudev\Downloads\WinMac\BootCamp-041-98143 -y c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\WindowsSupport.dmg


7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 1613846904 bytes (1540 MiB)

Extracting archive: c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\WindowsSupport.dmg
--
Path = c:\users\gurudev\appdata\local\temp\bootcamp-unpack_ohjgru\WindowsSupport.dmg
Type = Dmg
Physical Size = 1613846904
Method = Copy ZLIB CRC
Blocks = 10602
----
Path = 0.Apple_ISO
Size = 2779248640
Packed Size = 1613213990
CRC = AFCB68E6
Comment = BOOTCAMP (Apple_ISO : 0)
Method = Copy ZLIB CRC
--
Path = 0.Apple_ISO
Type = Iso
Physical Size = 2779248640
Created = 2016-04-01 01:37:10.00
Modified = 2016-04-01 01:37:10.00

Everything is Ok

Folders: 337
Files: 2455
Size:       2775039248
Compressed: 1613846904
Done.

**Comment by b-** [comment]
Invoking brigadier as administrator solves the 7zip install issue.

**Comment by awakey1** [comment]
> I got the same error. After installing 7-zip manually, it was gone.

um hello sorry i’m new to this type of stuff but i’m having the same problem, and wanted to ask what do you mean by installing 7zip manually? did you just install it like normal or were there other things you did?

**Comment by b-** [comment]
> um

Just install 7-zip as you would in any ordinary case, from their website. Or run brigadier as administrator and it will do it for you.

The bug is that it still tries to download and install 7-zip if you run it without privileges, and that fails. 

(I think a solution would be to either download and run in portable mode, or error out if 7-zip isn't installed and brigadier is not run as admin)
