### ISSUE TITLE
Trying to open brigadier and it immediately closes, ive went to power shell and tried to do it manually but it still doesn’t work, i have tried the -i, -o, and -m commands but still no dice.

### ISSUE THREAD

**Issue by awakey1** [timsutton/brigadier#87]
PS C: \Users \Zackaria Dieng\Downloads\brigadier-0.2.6> . \brigadier .exe -m MacBookA1r7,2
Using Mac model: MacBookAir7,2.
Traceback (most recent call last):
File "brigadier", line 379, in <module› File "brigadier", line 203, in main File "urli1b2.py"
File
, line 154, in urlopen
"url11b2.py
line 429, in open
file "urll1b2.py"
, line 447, in _open
File
"url11b2.py"
, line 407, in _call_chain
File "url11b2.py"
, line 1241, in https_open
File "urllib2.py", line 1198, in do open ur111b2.URLError: <urlopen error (Errno 11091] getaddrinfo falled›
[7204] Falled to execute script brigadier
PS C: \Users\Zackarla Dieng\Downloads \brigadier-0.2.6> •\brigadier.exe -o OUTPUT_DIR
Output directory OUTPUT_DIR that was specified doesn't existl
PS C: \Users \Zackaria Dieng\Downloads \brigadier-0.2.6> •\brigadier.exe -o OUTPUT_ DIR Downloads
Output directory OUTPUT _DIR that was specified doesn't existl p§ C: \Users\Zackaria Dieng \Downloads\brigadier-0.2.6>
•\brigadier.exe -1
Using Mac model: MacBookAir7,2.
Traceback (most recent call last):
File "brigadier"
line 379, in ‹module>
File "brigadier", . line 203, In main
File
"url11b2.py"
, line 154, in urlopen
File "url11b2.py'
line 429, in open
File "url11b2.py"
, line 447, in
_open
File "url11b2.py"
• line 407, in call chain
File "url11b2.py"
line 1241, In https _open
File "url11b2.py", line 1198, in do_open ur111b2.URLError: curlopen error (Errno 11001] getaddrinfo falled>
[7404] Falled to execute script brigadier

**Comment by benabi2** [comment]
same issue here
